// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica_2.Models;

namespace Practica_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211014223522_Corrigiendo Posts")]
    partial class CorrigiendoPosts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Practica_2.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("geoId")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .HasColumnType("longtext");

                    b.Property<string>("suite")
                        .HasColumnType("longtext");

                    b.Property<string>("zipcode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("geoId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Practica_2.Models.AlbumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Practica_2.Models.Geo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("lat")
                        .HasColumnType("longtext");

                    b.Property<string>("lng")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Geo");
                });

            modelBuilder.Entity("Practica_2.Models.PhotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlbumModelId")
                        .HasColumnType("int");

                    b.Property<string>("albumId")
                        .HasColumnType("longtext");

                    b.Property<string>("thumbnailUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumModelId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Practica_2.Models.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("body")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userIdId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Practica_2.Models.ToDoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.Property<bool>("completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .HasColumnType("longtext");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("Practica_2.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("addressId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("addressId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Practica_2.Models.Address", b =>
                {
                    b.HasOne("Practica_2.Models.Geo", "geo")
                        .WithMany()
                        .HasForeignKey("geoId");

                    b.Navigation("geo");
                });

            modelBuilder.Entity("Practica_2.Models.AlbumModel", b =>
                {
                    b.HasOne("Practica_2.Models.UserModel", null)
                        .WithMany("AlbumList")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Practica_2.Models.PhotoModel", b =>
                {
                    b.HasOne("Practica_2.Models.AlbumModel", null)
                        .WithMany("PhotosList")
                        .HasForeignKey("AlbumModelId");
                });

            modelBuilder.Entity("Practica_2.Models.PostModel", b =>
                {
                    b.HasOne("Practica_2.Models.UserModel", "userId")
                        .WithMany("PostsList")
                        .HasForeignKey("userIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userId");
                });

            modelBuilder.Entity("Practica_2.Models.ToDoModel", b =>
                {
                    b.HasOne("Practica_2.Models.UserModel", null)
                        .WithMany("ToDoList")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Practica_2.Models.UserModel", b =>
                {
                    b.HasOne("Practica_2.Models.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressId");

                    b.Navigation("address");
                });

            modelBuilder.Entity("Practica_2.Models.AlbumModel", b =>
                {
                    b.Navigation("PhotosList");
                });

            modelBuilder.Entity("Practica_2.Models.UserModel", b =>
                {
                    b.Navigation("AlbumList");

                    b.Navigation("PostsList");

                    b.Navigation("ToDoList");
                });
#pragma warning restore 612, 618
        }
    }
}
